apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-ext
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Grafana"
spec:
  # On production clusters, consider setting up auth for grafana, and
  # exposing Grafana either using a LoadBalancer or a public IP.
  type: NodePort
  ports:
    - port: 80
      targetPort: 8086
  selector:
    k8s-app: influxGrafana
